---
title: "CoreLogic Exploration 2"
author: "Zachary Goldstein"
date: "2023-03-26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(magrittr)
library(stringr)
```

# Combine ~150 files together

```{r}
folder_path = "data/property_basic2_20210728_110001_data/"
property_basics2_files = list.files(folder_path,pattern="*.csv")
df_pb2_raw = data.frame()
for (file in property_basics2_files){
  file_path = str_glue("{folder_path}/{file}")
  data = read.csv(file_path)
  df_pb2_raw = rbind(df_pb2_raw,data)
}
dim(df_pb2_raw)
head(df_pb2_raw)
```

```{r}
df_pb2 = df_pb2_raw %>%  
  slice_tail(n=nrow(df_pb2_raw)-1) %>% 
  mutate(across(all_of(c("YEAR.BUILT","NUMBER.OF.BUILDINGS",
                         "EFFECTIVE.YEAR.BUILT","NUMBER.OF.UNITS",
                         "ACRES","LAND.SQUARE.FOOTAGE",
                         "UNIVERSAL.BUILDING.SQUARE.FEET",
                         "BUILDING.SQUARE.FEET")),as.numeric))
names(df_pb2) = sapply(names(df_pb2),FUN=\(x){str_replace_all(x,"\\.","_") %>% str_to_lower()})
df_pb2 %>% 
  head()
```
```{r}
# MF = multi-family
df_pb2 %>% write.csv("data/corelogic_pb2_mf.csv",row.names=F)
```


```{r}
ggplot(df_pb2 %>% 
         filter(number_of_units<100,number_of_units>=5)) +
  geom_histogram(aes(x=number_of_units),color='white',
                 bins=95)
```
```{r}
df_pb2 %>% 
  count(situs_city,situs_state,fips_code) %>% 
  arrange(desc(n)) %>% 
  head(20)
```

```{r}
ggplot(df_pb2 %>% filter(year_built>=1860)) +
  geom_histogram(aes(x=year_built),color='white',
                 bins=30)
```
```{r}
ggplot(df_pb2 %>% filter(effective_year_built>=1880)) +
  geom_histogram(aes(x=effective_year_built),color='white',
                 bins=30)
```
```{r}
df_pb2 %>% 
  filter(situs_city=='SAN FRANCISCO',situs_state=='CA',number_of_units<=100,
          year_built>=2016) %>% 
  ggplot() +
  geom_histogram(aes(x=number_of_units),color='white',bins=50) +
  scale_x_continuous(n.breaks=20)
```

not great data in Portland OR
```{r}
df_pb2 %>% 
  filter(situs_city=='PORTLAND',situs_state=='OR',number_of_units<=100,
          year_built>=2016) %>% 
  ggplot() +
  geom_histogram(aes(x=number_of_units),color='white',bins=50) +
  scale_x_continuous(n.breaks=20)
```
```{r}

```

